[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake", "pkg-config", "libusb1", "libudev"]

[phases.install]
cmds = ["npm ci"]

[variables]
PYTHON = "python3"
PKG_CONFIG_PATH = "/usr/lib/pkgconfig:/usr/local/lib/pkgconfig"